### ISSUE TITLE
Qustion about the train.csv/test.csv?

### ISSUE THREAD

**Issue by mengxingkong** [Raschka-research-group/coral-cnn#22]
I want to know how to generate the .csv files that you provided in this project?

When I scan the .csv files and the images data, I find that the age in .csv file is not consistent with the original image file.

there is an example: in the .csv file the age is 15, but in the image name ,the age is 29, and 29 is more confidable. in the csv file, there are many problems like this.
![1](https://user-images.githubusercontent.com/22972773/80306754-b9acc180-87f7-11ea-818c-0c8c3e098702.png)

![image](https://user-images.githubusercontent.com/22972773/80307692-3db57800-87fd-11ea-9253-87f61e8e6522.png)

**Comment by rasbt** [comment]
Here, i subtracted constants so that the class labels numbers start at 0 for each dataset. This is not necessary for CORAL but for the regular cross-entropy-based classification approach. 

So in this case, the dataset CSV was prepared by subtracting the constant "14" from all class labels. 

You can see the section "Labels and train/test splits" in the README for the number range details for each dataset: https://github.com/Raschka-research-group/coral-cnn#labels-and-traintest-splits

**Comment by mengxingkong** [comment]
> Here, i subtracted constants so that the class labels numbers start at 0 for each dataset. This is not necessary for CORAL but for the regular cross-entropy-based classification approach.
> 
> So in this case, the dataset CSV was prepared by subtracting the constant "14" from all class labels.
> 
> You can see the section "Labels and train/test splits" in the README for the number range details for each dataset: https://github.com/Raschka-research-group/coral-cnn#labels-and-traintest-splits

Thanks for your reply! I understand.

**Comment by rasbt** [comment]
Great! I am glad that I could clear this up!
